import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const EFFECTIVE_DATE = 'January 1, 2026';

export default function Terms() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-200 bg-white sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center gap-4">
          <Link to="/" className="flex items-center gap-2 text-slate-600 hover:text-slate-900 transition-colors">
            <ArrowLeft className="h-4 w-4" />
            <span className="text-sm font-medium">Home</span>
          </Link>
          <div className="flex gap-4 ml-auto text-sm">
            <Link to="/legal/privacy" className="text-slate-500 hover:text-slate-900">Privacy</Link>
            <Link to="/legal/disclosures" className="text-slate-500 hover:text-slate-900">Disclosures</Link>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-slate-500 mb-10">Effective: {EFFECTIVE_DATE}</p>

        <div className="prose prose-slate max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-slate-900">1. Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              By accessing or using the Edge platform ("Platform"), you agree to be bound by these
              Terms of Use ("Terms"). If you do not agree, do not use the Platform. Edge is a product
              of IAB Advisors, Inc. ("Company", "we", "our").
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">2. Description of Service</h2>
            <p className="text-slate-600 leading-relaxed">
              Edge provides AI-powered investment analytics, portfolio reporting, compliance tools,
              and client communication features for registered investment advisors ("RIAs") and their
              clients. The Platform is designed to augment—not replace—the professional judgment of
              qualified financial advisors.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">3. Not Investment Advice</h2>
            <p className="text-slate-600 leading-relaxed">
              <strong>The Platform does not provide investment advice.</strong> All content,
              analytics, projections, and AI-generated narratives are informational in nature.
              Investment decisions should be made in consultation with a qualified financial
              professional. Past performance does not guarantee future results.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">4. User Accounts & Responsibilities</h2>
            <p className="text-slate-600 leading-relaxed">
              You are responsible for maintaining the confidentiality of your account credentials
              and for all activities under your account. RIA users are responsible for ensuring
              their use of the Platform complies with all applicable securities laws and regulations.
              You agree to notify us immediately of any unauthorized access to your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">5. Intellectual Property</h2>
            <p className="text-slate-600 leading-relaxed">
              All AI models, algorithms, training methodologies, data processing pipelines, user
              interfaces, documentation, and other aspects of the Platform are proprietary intellectual
              property of IAB Advisors, Inc. and are protected by applicable trade secret, copyright,
              and other intellectual property laws. You may not reverse engineer, decompile, disassemble,
              or attempt to derive the source code or algorithms of any part of the Platform.
            </p>
            <p className="text-slate-600 leading-relaxed mt-2">
              Content generated by the Platform on your behalf (such as narratives, reports, and analytics)
              may be used by you for your legitimate business purposes. However, the underlying models,
              processes, and technology used to generate such content remain our exclusive property.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">6. Data Ownership</h2>
            <p className="text-slate-600 leading-relaxed">
              You retain ownership of all data you upload to the Platform. We process your data solely
              to provide the services described herein and in accordance with our{' '}
              <Link to="/legal/privacy" className="text-blue-600 hover:text-blue-700 underline">Privacy Policy</Link>.
              We do not sell, share, or use your data for training models for other customers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">7. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, IAB ADVISORS, INC. SHALL NOT BE LIABLE FOR
              ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING
              WITHOUT LIMITATION LOSS OF PROFITS, DATA, USE, OR GOODWILL, ARISING OUT OF OR RELATED
              TO YOUR USE OF THE PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT, NEGLIGENCE,
              STRICT LIABILITY, OR ANY OTHER LEGAL THEORY.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">8. Modifications</h2>
            <p className="text-slate-600 leading-relaxed">
              We reserve the right to modify these Terms at any time. Material changes will be
              communicated via email or in-platform notification at least 30 days prior to taking
              effect. Continued use of the Platform following such notice constitutes acceptance
              of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">9. Governing Law</h2>
            <p className="text-slate-600 leading-relaxed">
              These Terms are governed by the laws of the State of Delaware without regard to
              conflict-of-law principles. Any disputes arising from these Terms or use of the
              Platform shall be resolved in the federal or state courts located in Wilmington, Delaware.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">10. Contact</h2>
            <p className="text-slate-600 leading-relaxed">
              If you have questions about these Terms, contact us at{' '}
              <a href="mailto:legal@edge.com" className="text-blue-600 hover:text-blue-700 underline">legal@edge.com</a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
