"""add_quantity_to_automations

Revision ID: 213574eb3fd0
Revises: 3a2807af4be6
Create Date: 2026-01-06 14:51:43.595192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213574eb3fd0'
down_revision = '3a2807af4be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
