"""Add feedback table for beta testing

Revision ID: 3a2807af4be6
Revises: d1f84adc3104
Create Date: 2025-12-15 19:08:29.208502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2807af4be6'
down_revision = 'd1f84adc3104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rsi_enabled', sa.Boolean(), nullable=True),
    sa.Column('rsi_oversold_threshold', sa.Float(), nullable=True),
    sa.Column('rsi_overbought_threshold', sa.Float(), nullable=True),
    sa.Column('ma_enabled', sa.Boolean(), nullable=True),
    sa.Column('require_golden_cross', sa.Boolean(), nullable=True),
    sa.Column('require_death_cross', sa.Boolean(), nullable=True),
    sa.Column('min_ma_separation_percent', sa.Float(), nullable=True),
    sa.Column('macd_enabled', sa.Boolean(), nullable=True),
    sa.Column('require_macd_bullish', sa.Boolean(), nullable=True),
    sa.Column('require_macd_bearish', sa.Boolean(), nullable=True),
    sa.Column('min_macd_histogram', sa.Float(), nullable=True),
    sa.Column('volume_enabled', sa.Boolean(), nullable=True),
    sa.Column('min_volume_ratio', sa.Float(), nullable=True),
    sa.Column('require_volume_confirmation', sa.Boolean(), nullable=True),
    sa.Column('price_change_enabled', sa.Boolean(), nullable=True),
    sa.Column('min_price_change_percent', sa.Float(), nullable=True),
    sa.Column('max_price_change_percent', sa.Float(), nullable=True),
    sa.Column('support_resistance_enabled', sa.Boolean(), nullable=True),
    sa.Column('near_support_threshold', sa.Float(), nullable=True),
    sa.Column('near_resistance_threshold', sa.Float(), nullable=True),
    sa.Column('min_signal_count', sa.Integer(), nullable=True),
    sa.Column('require_all_signals_bullish', sa.Boolean(), nullable=True),
    sa.Column('require_all_signals_bearish', sa.Boolean(), nullable=True),
    sa.Column('iv_enabled', sa.Boolean(), nullable=True),
    sa.Column('min_iv_rank', sa.Float(), nullable=True),
    sa.Column('max_iv_rank', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_filters_user_id'), ['user_id'], unique=True)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('browser_info', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('target_delta', sa.Float(), nullable=True),
    sa.Column('target_theta', sa.Float(), nullable=True),
    sa.Column('target_vega', sa.Float(), nullable=True),
    sa.Column('entry_iv_rank_min', sa.Float(), nullable=True),
    sa.Column('entry_iv_rank_max', sa.Float(), nullable=True),
    sa.Column('profit_target_percent', sa.Float(), nullable=True),
    sa.Column('stop_loss_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('leg_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('contract_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('entry_delta', sa.Float(), nullable=True),
    sa.Column('entry_gamma', sa.Float(), nullable=True),
    sa.Column('entry_theta', sa.Float(), nullable=True),
    sa.Column('entry_vega', sa.Float(), nullable=True),
    sa.Column('entry_iv', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('filled', sa.Boolean(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_legs_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_legs_strategy_id'))

    op.drop_table('strategy_legs')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategies_symbol'))

    op.drop_table('strategies')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))

    op.drop_table('feedback')
    with op.batch_alter_table('alert_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_filters_user_id'))

    op.drop_table('alert_filters')
    # ### end Alembic commands ###
