"""Initial migration

Revision ID: 809ba38b40c9
Revises: 
Create Date: 2025-12-01 18:13:24.480518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809ba38b40c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This is a fresh database, so we skip drop statements
    # The downgrade function contains the table creation logic
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('strategy_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('target_delta', sa.FLOAT(), nullable=True),
    sa.Column('target_theta', sa.FLOAT(), nullable=True),
    sa.Column('target_vega', sa.FLOAT(), nullable=True),
    sa.Column('entry_iv_rank_min', sa.FLOAT(), nullable=True),
    sa.Column('entry_iv_rank_max', sa.FLOAT(), nullable=True),
    sa.Column('profit_target_percent', sa.FLOAT(), nullable=True),
    sa.Column('stop_loss_percent', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_symbol'), ['symbol'], unique=False)

    op.create_table('strategy_legs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), nullable=False),
    sa.Column('leg_number', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), nullable=False),
    sa.Column('contract_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('strike_price', sa.FLOAT(), nullable=False),
    sa.Column('expiration_date', sa.DATE(), nullable=False),
    sa.Column('entry_delta', sa.FLOAT(), nullable=True),
    sa.Column('entry_gamma', sa.FLOAT(), nullable=True),
    sa.Column('entry_theta', sa.FLOAT(), nullable=True),
    sa.Column('entry_vega', sa.FLOAT(), nullable=True),
    sa.Column('entry_iv', sa.FLOAT(), nullable=True),
    sa.Column('entry_price', sa.FLOAT(), nullable=True),
    sa.Column('filled', sa.BOOLEAN(), nullable=True),
    sa.Column('filled_at', sa.DATETIME(), nullable=True),
    sa.Column('position_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_legs_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###
