/**
 * Export utilities for CSV and PDF generation
 */

// CSV Export
export function exportToCSV(
  data: Record<string, unknown>[],
  filename: string,
  columns: { key: string; header: string }[]
) {
  // Build header row
  const headers = columns.map(c => c.header).join(',');
  
  // Build data rows
  const rows = data.map(row => 
    columns.map(col => {
      let value = row[col.key];
      // Convert to string
      if (value === null || value === undefined) {
        value = '';
      } else if (typeof value !== 'string') {
        value = String(value);
      }
      // Escape commas and quotes
      if (typeof value === 'string' && (value.includes(',') || value.includes('"') || value.includes('\n'))) {
        value = `"${value.replace(/"/g, '""')}"`;
      }
      return value;
    }).join(',')
  );
  
  // Combine and download
  const csvContent = [headers, ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `${filename}.csv`);
}

// JSON Export (for backup/import)
export function exportToJSON(data: unknown, filename: string) {
  const jsonContent = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonContent], { type: 'application/json' });
  downloadBlob(blob, `${filename}.json`);
}

// PDF Export (opens printable HTML in new window)
export function exportToPDF(title: string, content: string, _filename: string) {
  // For a real PDF, you'd use jsPDF or similar
  // This creates a printable HTML page that can be saved as PDF
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px;
          max-width: 900px;
          margin: 0 auto;
          color: #333;
          line-height: 1.6;
        }
        h1 { 
          color: #1a1a1a; 
          border-bottom: 2px solid #3b82f6; 
          padding-bottom: 10px;
          margin-bottom: 20px;
        }
        h2 { color: #374151; margin-top: 30px; }
        table { 
          width: 100%; 
          border-collapse: collapse; 
          margin: 20px 0;
          font-size: 14px;
        }
        th, td { 
          padding: 12px; 
          text-align: left; 
          border-bottom: 1px solid #e5e7eb; 
        }
        th { 
          background: #f9fafb; 
          font-weight: 600;
          text-transform: uppercase;
          font-size: 11px;
          letter-spacing: 0.05em;
          color: #6b7280;
        }
        tr:hover { background: #f9fafb; }
        .pass { color: #16a34a; font-weight: 600; }
        .fail { color: #dc2626; font-weight: 600; }
        .warning { color: #d97706; font-weight: 600; }
        .footer { 
          margin-top: 40px; 
          padding-top: 20px; 
          border-top: 1px solid #e5e7eb; 
          font-size: 12px; 
          color: #6b7280;
        }
        .summary-box {
          background: #f9fafb;
          border: 1px solid #e5e7eb;
          border-radius: 8px;
          padding: 20px;
          margin: 20px 0;
        }
        .summary-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 20px;
        }
        .summary-item {
          text-align: center;
        }
        .summary-value {
          font-size: 24px;
          font-weight: 700;
        }
        .summary-label {
          font-size: 12px;
          color: #6b7280;
          text-transform: uppercase;
        }
        @media print {
          body { padding: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">
        <p>Generated by Edge Platform</p>
        <p>IAB Advisors, Inc. | ${new Date().toLocaleString()}</p>
        <p>This report is confidential and intended for authorized recipients only.</p>
      </div>
      <script>
        // Auto-trigger print dialog
        window.onload = function() {
          window.print();
        };
      </script>
    </body>
    </html>
  `);
  
  printWindow.document.close();
}

// Helper to download blob
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
